//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPIAccess
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string OrgCode { get; set; }
        public string Path { get; set; }
    }
}
