//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditMonitoring
    {
        public string UserGDSId { get; set; }
        public string TravellerName { get; set; }
        public string DateRetrieved { get; set; }
        public string TimeRetrieved { get; set; }
        public int ID { get; set; }
    }
}
