//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonAirTransaction
    {
        public string ProductCode { get; set; }
        public string SubProduct { get; set; }
        public string CP { get; set; }
        public string CPAccess { get; set; }
        public string VendorCode { get; set; }
        public string VendorAccess { get; set; }
        public string Cost { get; set; }
        public string CostAccess { get; set; }
        public string SAAmount { get; set; }
        public string SAAccess { get; set; }
        public string Remarks { get; set; }
        public string travelType { get; set; }
        public string RefFare { get; set; }
        public string LowFare { get; set; }
        public string EC { get; set; }
        public string DateHotel { get; set; }
    }
}
