//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSetting
    {
        public string ProductName { get; set; }
        public string ProductCategory { get; set; }
        public string Remarks { get; set; }
        public string SubProdAccess { get; set; }
        public string CommPercentage { get; set; }
        public string CommAccess { get; set; }
        public string Vendor { get; set; }
        public string VendorAccess { get; set; }
        public string CostAmount { get; set; }
        public string CostAccess { get; set; }
        public string SFAmount { get; set; }
        public string SFAccess { get; set; }
        public int ID { get; set; }
    }
}
