//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileAgentInfo
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string InitialSignIn { get; set; }
        public string QueueNo { get; set; }
        public string TeamGroup { get; set; }
        public string ContactNo { get; set; }
        public string AP { get; set; }
        public string Div { get; set; }
        public string CompanyName { get; set; }
        public string Remarks { get; set; }
        public string Others { get; set; }
        public string Status { get; set; }
        public string AccessLevel { get; set; }
        public string CreditCardAccess { get; set; }
        public string GDSSignIn { get; set; }
        public int ID { get; set; }
    }
}
