//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmittal
    {
        public string ProfileNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceAmount { get; set; }
        public string AttentionTo { get; set; }
        public string PreparedBy { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
    }
}
