//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public string AccessLevel { get; set; }
        public string ClientNo { get; set; }
        public string DivisionNo { get; set; }
        public string BookingAgent { get; set; }
        public string VesselName { get; set; }
        public string PhoneElement { get; set; }
        public string Compleat { get; set; }
        public string ReceivedFrom { get; set; }
        public string TKTL { get; set; }
        public string ClientName { get; set; }
        public string VName { get; set; }
        public string BillTo { get; set; }
        public string Mandatory { get; set; }
        public int ID { get; set; }
    }
}
