//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAIS_Server_NewGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public string VesselNo { get; set; }
        public string VesselName { get; set; }
        public string Principal { get; set; }
        public string SubPrincipal { get; set; }
        public string Remarks { get; set; }
        public string Others { get; set; }
    }
}
